name: Build and Deploy Docker Image Dev

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Execute Docker commands on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/leo/remote_docker_folder
          docker rmi $(docker images focus-flow-image -q)
          docker build --no-cache -t focus-flow-image:dev -f Dockerfile-dev .
          docker compose up -d --build focus-flow-dev
        EOF
