name: Build and Deploy Docker Image Dev

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh

    - name: Connect to Tailscale
      env:
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
      run: |
        sudo tailscale up --authkey=${TAILSCALE_AUTH_KEY}


    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Debug SSH connection
      run: |
        ssh -vvv -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}


    - name: Execute Docker commands on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ~/works
          docker ps -q --filter "ancestor=focus-flow-image:dev"
          docker stop $(docker ps -q --filter "ancestor=focus-flow-image:dev") || true
          docker rm $(docker ps -aq --filter "ancestor=focus-flow-image:dev") || true
          docker rmi -f focus-flow-image:dev
          docker build --no-cache -t focus-flow-image:dev -f Dockerfile-dev .
          docker-compose up -d --build focus-flow-service-dev
        EOF


